In [3]:
#Q1  Import the numpy package under the name `np`
import numpy as np


In [4]:
# 2. Print the numpy version and the configuration 

print(np.__version__)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/psinha/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/psinha/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/psinha/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/psinha/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP,ASIMDDP
    not found = ASIMDFHM
None


In [5]:
#3. Create a null vector of size 10 
array = np.zeros(10)
print (array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# 4. How to find the memory size of any array
print (array.size)

10


In [7]:
# 5. How to get the documentation of the numpy add function from the command line?
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [9]:
# 6  Create a null vector of size 10 but the fifth value which is 1 
array = np.zeros(10)
array[4] = 1
print (array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
# 7 Create a vector with values ranging from 10 to 49 
v = np.arange(10,49)
print (v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [11]:
# 8 Reverse a vector (first element becomes last)
print (np.flip(v))

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [12]:
#9 Create a 3x3 matrix with values ranging from 0 to 8 
x = np.arange(0,9).reshape(3,3)
print (x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#10  Find indices of non-zero elements from [1,2,0,0,4,0] 
x = [1,2,0,0,4,0]
print (np.nonzero(x))

(array([0, 1, 4]),)


In [14]:
#11 Create a 3x3 identity matrix 
print (np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# Create a 3x3x3 array with random values
x = np.random.random((3, 3, 3))
print (x)

[[[0.93873982 0.49607624 0.31661716]
  [0.92835441 0.68911263 0.03740193]
  [0.46764217 0.27241372 0.67090253]]

 [[0.83799113 0.85985535 0.1713516 ]
  [0.91978537 0.86655501 0.94893591]
  [0.69576603 0.49579014 0.79921893]]

 [[0.19531269 0.88705031 0.58609649]
  [0.78551115 0.57043566 0.57088787]
  [0.59436023 0.08161668 0.1773622 ]]]


In [16]:
#13 Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.random((10, 10))
print (x.max())

0.9817723983349517


In [17]:
#14 Create a random vector of size 30 and find the mean value
x = np.random.random(30)
print (x.mean())


0.47356913338078477


In [18]:
# 15. Create a 2d array with 1 on the border and 0 inside
x = np.ones((5,5))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
#16. How to add a border (filled with 0's) around an existing array?
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [20]:
# 17. What is the result of the following expression? 
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])

True

In [34]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1 
x[::2, 1::2] = 1  

print (x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [22]:
# 21. Create a checkerboard 8x8 matrix using the tile function

array = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [39]:
#22 Normalize a 5x5 random matrix
nums = np.random.rand(5,5)
col_means = np.mean(nums, axis=0)
arr_normalized = (nums - col_means) / np.std(nums, axis=0)
print (arr_normalized)

[[ 0.6064286   0.34023401  1.06615461 -1.25777682 -0.48676584]
 [ 1.22656353 -1.41048328 -1.33441131  0.14219749 -1.29004453]
 [-1.65596743 -0.86858386  0.94878833  1.50151493  1.54111959]
 [ 0.34153954  0.60830517  0.34926296 -0.9239798   0.70776889]
 [-0.51856424  1.33052796 -1.02979459  0.5380442  -0.47207811]]


In [23]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x, y)

print (z)

[[0.63428665 0.83313754]
 [0.53784764 1.10388701]
 [0.26707024 0.30715066]
 [0.24463803 0.3991558 ]
 [0.53639466 0.72917516]]


In [24]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

arr=np.arange(10)
condition = np.logical_and(arr >= 3, arr <= 8)
arr = np.select([~condition, condition], [arr, -arr])
print (arr)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


In [25]:
# 26 What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [26]:
#  28. What are the result of the following expressions?
#np.array(0) / np.array(0)
#np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/_q/0lsnh08n6wb_6xwxh8zl2p000000gp/T/ipykernel_1546/2794363542.py:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

In [27]:
# 29. How to round away from zero a float array ?
def round_array(x,y):
    return np.round(x,y)

test = np.array([32.11, 51.5, 0.112])
print(round_array(test,0))

[32. 52.  0.]


In [28]:
# 30. How to find common values between two arrays? 
a = np.array([2, 4, 7, 1, 4]) 
b = np.array([7, 2, 9, 0, 5])

c = np.intersect1d(a, b)

print (c)

[2 7]


In [30]:
# 32 Is the following expressions true?

#np.sqrt(-1) == np.emath.sqrt(-1)

np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/_q/0lsnh08n6wb_6xwxh8zl2p000000gp/T/ipykernel_1546/942046139.py:5: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [31]:
# 33. How to get the dates of yesterday, today and tomorrow? 

today = np.datetime64('today', 'D') 
print("Today: ", today) 
  

yesterday = np.datetime64('today', 'D') 
- np.timedelta64(1, 'D') 
  
print("Yestraday: ", yesterday) 
  

tomorrow = np.datetime64('today', 'D') 
+ np.timedelta64(1, 'D') 
  
print("Tomorrow: ", tomorrow) 

Today:  2024-02-05
Yestraday:  2024-02-05
Tomorrow:  2024-02-05


In [32]:
#34 How to get all the dates corresponding to the month of July 2016?

array = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(array)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [33]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

In [34]:
#36. Extract the integer part of a random array of positive numbers

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


[5. 7. 5. 6. 0. 5. 4. 9. 2. 1.]
[5. 7. 5. 6. 0. 5. 4. 9. 2. 1.]
[5. 7. 5. 6. 0. 5. 4. 9. 2. 1.]
[5 7 5 6 0 5 4 9 2 1]
[5. 7. 5. 6. 0. 5. 4. 9. 2. 1.]


In [35]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4 
x = np.zeros((5,5))
x += np.arange(5)
print (x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [36]:
# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [37]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 
x = np.linspace(0, 1, 11, endpoint=False)[1:-1]
print (x)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [38]:
#40 Create a random vector of size 10 and sort it 
x = np.random.random(10)
x.sort()
print (x)

[0.04694595 0.08305531 0.15397086 0.3641225  0.46659989 0.70546732
 0.78535492 0.94836472 0.96717004 0.97422999]


In [39]:
# 41 How to sum a small array faster than np.sum?

# we can sum faster than np.sum by using python Sum

In [40]:
#  42. Consider two random array A and B, check if they are equal
x = np.random.randint(0, 2, 6)
y = np.random.randint(0, 2, 6)
print(np.allclose(x, y))

False


In [41]:
# 43. Make an array immutable (read-only)
x = np.arange(10)
x.setflags(write=False)
print (x)
#x[2] = 0
print (x)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [42]:
# 44 Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)

print(r)

print(t)

[0.92550209 0.77003475 0.52980431 0.13463624 0.94725491 1.3708168
 0.59415166 0.87830341 0.98102942 1.03015869]
[1.45311891 1.03566727 1.00248451 1.43433827 0.00198376 0.75409526
 0.98770851 0.30438523 1.16058296 1.21371242]


In [43]:
# 45. Create random vector of size 10 and replace the maximum value by 0 
x = np.random.random(10)
print (x)
x[x.argmax()] = 0
print (x)


[0.42629547 0.95447478 0.55392111 0.53485832 0.51103974 0.11364449
 0.49152357 0.02909806 0.63345284 0.80638025]
[0.42629547 0.         0.55392111 0.53485832 0.51103974 0.11364449
 0.49152357 0.02909806 0.63345284 0.80638025]


In [44]:
# 46 Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

In [ ]:
# 48. Print the minimum and maximum representable value for each numpy scalar type

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

In [79]:
# 49. How to print all the values of an array? 

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[0 1]


In [45]:
# 50. How to find the closest value (to a given scalar) in a vector?

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


88
